# Generated by Django 4.1.3 on 2022-12-16 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lht_Averages',
            fields=[
                ('entry_id', models.AutoField(primary_key=True, serialize=False)),
                ('dev_uid', models.CharField(max_length=25)),
                ('entry_date', models.IntegerField()),
                ('BatV', models.FloatField()),
                ('Bat_status', models.IntegerField()),
                ('Hum_SHT', models.FloatField()),
                ('ILL_lx', models.FloatField(blank=True, default=None, null=True)),
                ('TempC_DS', models.FloatField(blank=True, default=None, null=True)),
                ('TempC_SHT', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='LhtEntries',
            fields=[
                ('entry_id', models.AutoField(primary_key=True, serialize=False)),
                ('dev_uid', models.CharField(max_length=25)),
                ('entry_date', models.DateTimeField()),
                ('BatV', models.FloatField()),
                ('Bat_status', models.IntegerField()),
                ('Hum_SHT', models.FloatField()),
                ('ILL_lx', models.FloatField(blank=True, default=None, null=True)),
                ('TempC_DS', models.FloatField(blank=True, default=None, null=True)),
                ('TempC_SHT', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Py_Averages',
            fields=[
                ('entry_id', models.AutoField(primary_key=True, serialize=False)),
                ('dev_uid', models.CharField(max_length=25)),
                ('entry_date', models.IntegerField()),
                ('light', models.FloatField()),
                ('temperature', models.FloatField()),
                ('pressure', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PyEntries',
            fields=[
                ('entry_id', models.AutoField(primary_key=True, serialize=False)),
                ('dev_uid', models.CharField(max_length=25)),
                ('entry_date', models.DateTimeField()),
                ('light', models.FloatField()),
                ('temperature', models.FloatField()),
                ('pressure', models.FloatField(default=0)),
            ],
        ),
    ]
