# Generated by Django 4.1.3 on 2022-12-01 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('dev_uid', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('type_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=20)),
                ('attributes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PyEntries',
            fields=[
                ('entry_id', models.AutoField(primary_key=True, serialize=False)),
                ('entry_date', models.DateTimeField()),
                ('light', models.FloatField()),
                ('temperature', models.FloatField()),
                ('dev_uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webserver.device')),
            ],
        ),
        migrations.CreateModel(
            name='LhtEntries',
            fields=[
                ('entry_id', models.AutoField(primary_key=True, serialize=False)),
                ('entry_date', models.DateTimeField()),
                ('BatV', models.FloatField()),
                ('Bat_status', models.IntegerField()),
                ('Hum_SHT', models.FloatField()),
                ('ILL_lx', models.FloatField()),
                ('TempC_SHT', models.FloatField()),
                ('Work_mode', models.TextField()),
                ('dev_uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webserver.device')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='device_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webserver.devicetype'),
        ),
    ]
