# Generated by Django 4.1.3 on 2022-12-16 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webserver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meta_data',
            fields=[
                ('entry_id', models.AutoField(primary_key=True, serialize=False)),
                ('dev_uid', models.CharField(max_length=25)),
                ('gateway_id', models.CharField(max_length=100)),
                ('loc_lon', models.DecimalField(decimal_places=16, max_digits=22)),
                ('loc_lat', models.DecimalField(decimal_places=16, max_digits=22)),
                ('loc_alt', models.DecimalField(decimal_places=16, max_digits=22)),
                ('rssi', models.IntegerField()),
                ('snr', models.FloatField()),
                ('airtime', models.FloatField()),
            ],
        ),
        migrations.RenameField(
            model_name='lht_averages',
            old_name='entry_date',
            new_name='entry_hour',
        ),
        migrations.RenameField(
            model_name='py_averages',
            old_name='entry_date',
            new_name='entry_hour',
        ),
        migrations.AlterField(
            model_name='lht_averages',
            name='ILL_lx',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='lht_averages',
            name='TempC_DS',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='lhtentries',
            name='ILL_lx',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='lhtentries',
            name='TempC_DS',
            field=models.FloatField(default=None),
        ),
    ]
