# Generated by Django 4.1.3 on 2022-12-17 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webserver', '0002_meta_data_rename_entry_date_lht_averages_entry_hour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lht_averages',
            name='ILL_lx',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='lht_averages',
            name='TempC_DS',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
