# Generated by Django 4.1.3 on 2022-12-02 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webserver', '0002_pyentries_pressure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lhtentries',
            name='Work_mode',
        ),
    ]
