# Generated by Django 4.1.3 on 2022-12-17 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webserver', '0003_alter_lht_averages_ill_lx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meta_data',
            name='loc_alt',
        ),
    ]
