# Generated by Django 4.1.3 on 2022-12-02 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webserver', '0003_remove_lhtentries_work_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='lhtentries',
            name='TempC_DS',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='lhtentries',
            name='ILL_lx',
            field=models.FloatField(default=None),
        ),
    ]
