# Generated by Django 4.1.3 on 2022-12-20 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webserver', '0005_rename_loc_lat_meta_data_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='py_averages',
            name='humidity',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='pyentries',
            name='humidity',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
